const ACHIEVEMENTS = [
  // --- Práctica general ---
  {
    id: 'first_steps',
    title: 'Primeros pasos',
    description: 'Practica por primera vez.',
    icon: 'fa-solid fa-shoe-prints',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.totalPracticeMinutes > 0,
    progress: (s) => ({ current: Math.min(s.totalPracticeMinutes, 1), target: 1 }),
  },
  {
    id: 'daily_goal_first',
    title: 'Meta diaria',
    description: 'Cumple tu objetivo diario por primera vez.',
    icon: 'fa-solid fa-bullseye',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.todayMinutes >= s.dailyGoalMinutes && s.dailyGoalMinutes > 0,
    progress: (s) => ({ current: Math.min(s.todayMinutes, s.dailyGoalMinutes), target: s.dailyGoalMinutes }),
  },
  {
    id: 'week_streak_3',
    title: 'Tres al hilo',
    description: 'Racha de 3 días practicando.',
    icon: 'fa-solid fa-calendar-check',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.streak.current >= 3,
    progress: (s) => ({ current: Math.min(s.streak.current, 3), target: 3 }),
  },
  {
    id: 'week_streak_7',
    title: 'Semana perfecta',
    description: 'Racha de 7 días.',
    icon: 'fa-solid fa-calendar-week',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.streak.current >= 7,
    progress: (s) => ({ current: Math.min(s.streak.current, 7), target: 7 }),
  },
  {
    id: 'week_streak_30',
    title: 'Mes perfecto',
    description: 'Racha de 30 días.',
    icon: 'fa-solid fa-calendar-alt',
    rarity: 'gold',
    secret: false,
    condition: (s) => s.streak.current >= 30,
    progress: (s) => ({ current: Math.min(s.streak.current, 30), target: 30 }),
  },
  {
    id: 'week_streak_100',
    title: 'Devoción',
    description: 'Racha de 100 días.',
    icon: 'fa-solid fa-fire',
    rarity: 'platinum',
    secret: false,
    condition: (s) => s.streak.current >= 100,
    progress: (s) => ({ current: Math.min(s.streak.current, 100), target: 100 }),
  },
  {
    id: 'goal_week',
    title: 'Cumplidor',
    description: 'Cumple la meta diaria 7 días seguidos.',
    icon: 'fa-solid fa-check-double',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.goalStreak >= 7,
    progress: (s) => ({ current: Math.min(s.goalStreak, 7), target: 7 }),
  },
  {
    id: 'goal_month',
    title: 'Disciplinado',
    description: 'Cumple la meta diaria 30 días seguidos.',
    icon: 'fa-solid fa-medal',
    rarity: 'gold',
    secret: false,
    condition: (s) => s.goalStreak >= 30,
    progress: (s) => ({ current: Math.min(s.goalStreak, 30), target: 30 }),
  },
  {
    id: 'night_owl',
    title: 'Búho nocturno',
    description: 'Practica después de las 22:00.',
    icon: 'fa-solid fa-moon',
    rarity: 'bronze',
    secret: true,
    condition: (s) => s.practicedLateNight,
    progress: (s) => ({ current: s.practicedLateNight ? 1 : 0, target: 1 }),
  },
  {
    id: 'early_bird',
    title: 'Madrugador',
    description: 'Practica antes de las 07:00.',
    icon: 'fa-solid fa-sun',
    rarity: 'bronze',
    secret: true,
    condition: (s) => s.practicedEarlyMorning,
    progress: (s) => ({ current: s.practicedEarlyMorning ? 1 : 0, target: 1 }),
  },

  // --- Entrenamiento de notas ---
  {
    id: 'note_trainee',
    title: 'Aprendiz',
    description: 'Completa 10 rondas de "Toca la nota".',
    icon: 'fa-solid fa-music',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.training.totalRounds >= 10,
    progress: (s) => ({ current: Math.min(s.training.totalRounds, 10), target: 10 }),
  },
  {
    id: 'note_intermediate',
    title: 'Entrenador',
    description: 'Completa 100 rondas de "Toca la nota".',
    icon: 'fa-solid fa-dumbbell',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.training.totalRounds >= 100,
    progress: (s) => ({ current: Math.min(s.training.totalRounds, 100), target: 100 }),
  },
  {
    id: 'note_master',
    title: 'Maestro de notas',
    description: 'Completa 500 rondas de "Toca la nota".',
    icon: 'fa-solid fa-graduation-cap',
    rarity: 'gold',
    secret: false,
    condition: (s) => s.training.totalRounds >= 500,
    progress: (s) => ({ current: Math.min(s.training.totalRounds, 500), target: 500 }),
  },
  {
    id: 'note_perfect_streak_10',
    title: 'Oído certero',
    description: '10 aciertos seguidos en notas.',
    icon: 'fa-solid fa-ear-listen',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.training.maxStreak >= 10,
    progress: (s) => ({ current: Math.min(s.training.maxStreak, 10), target: 10 }),
  },
  {
    id: 'note_perfect_streak_25',
    title: 'Francotirador',
    description: '25 aciertos seguidos en notas.',
    icon: 'fa-solid fa-crosshairs',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.training.maxStreak >= 25,
    progress: (s) => ({ current: Math.min(s.training.maxStreak, 25), target: 25 }),
  },
  {
    id: 'note_speed_demon',
    title: 'Rápido y certero',
    description: 'Acertar en menos de 1 s de media (mín. 20 rondas).',
    icon: 'fa-solid fa-bolt',
    rarity: 'gold',
    secret: false,
    condition: (s) => s.training.avgReactionTime < 1 && s.training.totalRounds >= 20,
    progress: (s) => ({ current: s.training.totalRounds >= 20 ? (s.training.avgReactionTime < 1 ? 1 : 0) : Math.min(s.training.totalRounds, 20), target: s.training.totalRounds >= 20 ? 1 : 20 }),
  },
  {
    id: 'note_all_strings',
    title: 'Todas las cuerdas',
    description: 'Acierta al menos una nota en cada cuerda.',
    icon: 'fa-solid fa-guitar',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.training.stringsHit >= 4,
    progress: (s) => ({ current: Math.min(s.training.stringsHit, 4), target: 4 }),
  },

  // --- Intervalos ---
  {
    id: 'interval_first',
    title: 'Primer intervalo',
    description: 'Completa tu primer intervalo.',
    icon: 'fa-solid fa-wave-square',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.intervals.totalRounds >= 1,
    progress: (s) => ({ current: Math.min(s.intervals.totalRounds, 1), target: 1 }),
  },
  {
    id: 'interval_trainee',
    title: 'Estudiante de intervalos',
    description: '25 intervalos completados.',
    icon: 'fa-solid fa-headphones',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.intervals.totalRounds >= 25,
    progress: (s) => ({ current: Math.min(s.intervals.totalRounds, 25), target: 25 }),
  },
  {
    id: 'interval_master',
    title: 'Oído absoluto relativo',
    description: '200 intervalos completados.',
    icon: 'fa-solid fa-ear-deaf',
    rarity: 'gold',
    secret: false,
    condition: (s) => s.intervals.totalRounds >= 200,
    progress: (s) => ({ current: Math.min(s.intervals.totalRounds, 200), target: 200 }),
  },
  {
    id: 'interval_streak_10',
    title: 'Cadena de intervalos',
    description: '10 intervalos acertados seguidos.',
    icon: 'fa-solid fa-link',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.intervals.maxStreak >= 10,
    progress: (s) => ({ current: Math.min(s.intervals.maxStreak, 10), target: 10 }),
  },
  {
    id: 'interval_streak_25',
    title: 'Oído de lince',
    description: '25 intervalos acertados seguidos.',
    icon: 'fa-solid fa-eye',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.intervals.maxStreak >= 25,
    progress: (s) => ({ current: Math.min(s.intervals.maxStreak, 25), target: 25 }),
  },
  {
    id: 'interval_all_types',
    title: 'Recorrido completo',
    description: 'Acierta al menos una vez cada uno de los 12 intervalos.',
    icon: 'fa-solid fa-circle-check',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.intervals.typesHit >= 12,
    progress: (s) => ({ current: Math.min(s.intervals.typesHit, 12), target: 12 }),
  },

  // --- Rutinas ---
  {
    id: 'routine_first',
    title: 'Primera rutina',
    description: 'Completa una rutina predefinida.',
    icon: 'fa-solid fa-list-check',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.routines.predefinedCompleted >= 1,
    progress: (s) => ({ current: Math.min(s.routines.predefinedCompleted, 1), target: 1 }),
  },
  {
    id: 'routine_custom',
    title: 'Creador',
    description: 'Crea tu primera rutina personalizada.',
    icon: 'fa-solid fa-pen-to-square',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.routines.customCreated >= 1,
    progress: (s) => ({ current: Math.min(s.routines.customCreated, 1), target: 1 }),
  },
  {
    id: 'routine_custom_done',
    title: 'Mi rutina',
    description: 'Completa una rutina personalizada.',
    icon: 'fa-solid fa-person-running',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.routines.customCompleted >= 1,
    progress: (s) => ({ current: Math.min(s.routines.customCompleted, 1), target: 1 }),
  },
  {
    id: 'routine_marathon',
    title: 'Maratonista',
    description: 'Completa una rutina de 20 minutos o más.',
    icon: 'fa-solid fa-hourglass-end',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.routines.marathonCompleted,
    progress: (s) => ({ current: s.routines.marathonCompleted ? 1 : 0, target: 1 }),
  },
  {
    id: 'routine_week',
    title: 'En la rutina',
    description: 'Completa 5 rutinas en una semana.',
    icon: 'fa-solid fa-repeat',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.routines.weeklyCompleted >= 5,
    progress: (s) => ({ current: Math.min(s.routines.weeklyCompleted, 5), target: 5 }),
  },

  // --- Afinación y técnica ---
  {
    id: 'tuner_all_strings',
    title: 'Afinado perfecto',
    description: 'Toca las 4 cuerdas en el afinador.',
    icon: 'fa-solid fa-sliders',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.tuner.stringsSeen >= 4,
    progress: (s) => ({ current: Math.min(s.tuner.stringsSeen, 4), target: 4 }),
  },
  {
    id: 'tuner_fast',
    title: 'Afinación relámpago',
    description: 'Toca las 4 cuerdas en menos de 30 s.',
    icon: 'fa-solid fa-stopwatch',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.tuner.fastAttempt,
    progress: (s) => ({ current: s.tuner.fastAttempt ? 1 : 0, target: 1 }),
  },
  {
    id: 'drop_d_user',
    title: 'Drop D',
    description: 'Usa la afinación Drop D.',
    icon: 'fa-solid fa-arrow-down',
    rarity: 'silver',
    secret: true,
    condition: (s) => s.settings.tuning === 'drop_d',
    progress: (s) => ({ current: s.settings.tuning === 'drop_d' ? 1 : 0, target: 1 }),
  },
  {
    id: 'custom_tuning_user',
    title: 'Inventor',
    description: 'Crea una afinación personalizada.',
    icon: 'fa-solid fa-wrench',
    rarity: 'silver',
    secret: true,
    condition: (s) => s.settings.tuning === 'custom',
    progress: (s) => ({ current: s.settings.tuning === 'custom' ? 1 : 0, target: 1 }),
  },
  {
    id: 'fretboard_explorer',
    title: 'Explorador',
    description: 'Toca notas en 12 trastes distintos.',
    icon: 'fa-solid fa-map',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.tuner.fretsSeen >= 12,
    progress: (s) => ({ current: Math.min(s.tuner.fretsSeen, 12), target: 12 }),
  },

  // --- Pistas y metrónomo ---
  {
    id: 'metronome_first',
    title: 'Al ritmo',
    description: 'Usa el metrónomo 1 minuto.',
    icon: 'fa-solid fa-clock',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.metronomeMinutes >= 1,
    progress: (s) => ({ current: Math.min(Math.floor(s.metronomeMinutes), 1), target: 1 }),
  },
  {
    id: 'backing_first',
    title: 'Sobre la pista',
    description: 'Practica 1 minuto con pista.',
    icon: 'fa-solid fa-compact-disc',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.backingMinutes >= 1,
    progress: (s) => ({ current: Math.min(Math.floor(s.backingMinutes), 1), target: 1 }),
  },
  {
    id: 'backing_upload',
    title: 'Mi pista',
    description: 'Sube tu propia pista.',
    icon: 'fa-solid fa-upload',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.uploadedTracksCount >= 1,
    progress: (s) => ({ current: Math.min(s.uploadedTracksCount, 1), target: 1 }),
  },
  {
    id: 'jam_10',
    title: 'Jam session',
    description: '10 minutos totales sobre pistas.',
    icon: 'fa-solid fa-drum',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.backingMinutes >= 10,
    progress: (s) => ({ current: Math.min(Math.floor(s.backingMinutes), 10), target: 10 }),
  },
  {
    id: 'jam_30',
    title: 'Improvisador',
    description: '30 minutos totales sobre pistas.',
    icon: 'fa-solid fa-record-vinyl',
    rarity: 'gold',
    secret: false,
    condition: (s) => s.backingMinutes >= 30,
    progress: (s) => ({ current: Math.min(Math.floor(s.backingMinutes), 30), target: 30 }),
  },

  // --- Especiales ---
  {
    id: 'all_rounder',
    title: 'Polivalente',
    description: 'Practica en 4 categorías distintas.',
    icon: 'fa-solid fa-star',
    rarity: 'gold',
    secret: true,
    condition: (s) => s.categoryCount >= 4,
    progress: (s) => ({ current: Math.min(s.categoryCount, 4), target: 4 }),
  },
  {
    id: 'perfectionist',
    title: 'Perfeccionista',
    description: '50 aciertos seguidos combinados (notas + intervalos).',
    icon: 'fa-solid fa-crown',
    rarity: 'gold',
    secret: true,
    condition: (s) => s.combinedMaxStreak >= 50,
    progress: (s) => ({ current: Math.min(s.combinedMaxStreak, 50), target: 50 }),
  },

  // --- Improvisación ---
  {
    id: 'impro_first',
    title: 'Improvisando',
    description: 'Completa 1 minuto en modo improvisación.',
    icon: 'fa-solid fa-guitar',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.improvisationMinutes >= 1,
    progress: (s) => ({ current: Math.min(Math.floor(s.improvisationMinutes), 1), target: 1 }),
  },
  {
    id: 'impro_10',
    title: 'Solo largo',
    description: '10 minutos improvisando.',
    icon: 'fa-solid fa-music',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.improvisationMinutes >= 10,
    progress: (s) => ({ current: Math.min(Math.floor(s.improvisationMinutes), 10), target: 10 }),
  },
  {
    id: 'impro_guided',
    title: 'Guiado',
    description: 'Completa una sesión con modo guiado.',
    icon: 'fa-solid fa-compass',
    rarity: 'bronze',
    secret: false,
    condition: (s) => s.improvisation.guidedSessions >= 1,
    progress: (s) => ({ current: Math.min(s.improvisation.guidedSessions, 1), target: 1 }),
  },
  {
    id: 'impro_bootsy',
    title: 'Bootsy Level',
    description: 'Completa una sesión en dificultad Bootsy Level.',
    icon: 'fa-solid fa-bolt',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.improvisation.bootsySessions >= 1,
    progress: (s) => ({ current: Math.min(s.improvisation.bootsySessions, 1), target: 1 }),
  },
  {
    id: 'impro_streak_20',
    title: 'Sin notas falsas',
    description: 'Racha de 20 en modo improvisación.',
    icon: 'fa-solid fa-fire',
    rarity: 'silver',
    secret: false,
    condition: (s) => s.improvisation.maxStreak >= 20,
    progress: (s) => ({ current: Math.min(s.improvisation.maxStreak, 20), target: 20 }),
  },
  {
    id: 'impro_jazz_5',
    title: 'Jazz cat',
    description: '5 minutos improvisando en estilo jazz.',
    icon: 'fa-solid fa-saxophone',
    rarity: 'silver',
    secret: true,
    condition: (s) => s.improvisation.jazzMinutes >= 5,
    progress: (s) => ({ current: Math.min(Math.floor(s.improvisation.jazzMinutes), 5), target: 5 }),
  },

  {
    id: 'collector',
    title: 'Coleccionista',
    description: 'Desbloquea 10 logros (sin contar eastereggs).',
    icon: 'fa-solid fa-box-archive',
    rarity: 'gold',
    secret: true,
    condition: (s) => s.totalUnlocked >= 10,
    progress: (s) => ({ current: Math.min(s.totalUnlocked, 10), target: 10 }),
  },
  {
    id: 'legend',
    title: 'Leyenda del bajo',
    description: 'Desbloquea 25 logros (sin contar eastereggs).',
    icon: 'fa-solid fa-trophy',
    rarity: 'platinum',
    secret: true,
    condition: (s) => s.totalUnlocked >= 25,
    progress: (s) => ({ current: Math.min(s.totalUnlocked, 25), target: 25 }),
  },
];

export { ACHIEVEMENTS };
